@echo off
REM Start backend server with FFmpeg in PATH
echo Starting KaamKhoj Backend Server...
echo Adding FFmpeg to PATH...
set PATH=%PATH%;C:\Program Files\ffmpeg\bin
echo.
echo Starting nodemon...
nodemon ./app.js
